# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - lint
          - checkdoc
          - mypy

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive


      - name: tox ${{ matrix.linter }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.linter }}
          MAGIC: /usr/lib/file/magic.mgc
        with:
          args: bash -c "apt-install libmagic-dev && tox"

  tests:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        toxenv:
          - py37
          - py38
          - py39
          - py310
          - py311

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: tox ${{ matrix.toxenv }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.toxenv }}
          AMQP_URL: amqp://guest:guest@rabbitmq
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          MAGIC: /usr/lib/file/magic.mgc
        with:
          args: bash -c "apt-install libmagic-dev && tox"
